name: Preflight Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Image build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OPM
        run: |
          make opm

      - name: Login to registry.redhat.io
        uses: docker/login-action@v3
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RH_USERNAME }}
          password: ${{ secrets.RH_TOKEN }}

      - name: Generate catalog
        run: |
          export PATH=$PATH:${PWD}/bin
          ./build/generate-catalog.sh
          git diff --exit-code

      - name: Validate catalog
        run: |
          make validate-catalog

      - name: Build and verify image
        run: |
          make build-image
          make run-image &
          pid=$!
          make test-image
          make stop-image
          wait ${pid}
